project_name: terraform-provider-fortiappseccloud

builds:
  - id: terraform-provider-fortiappseccloud
    main: main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w"
    artifacts:
      - name: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - terraform-registry-manifest.json

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  extra_files:
    - glob: "terraform-registry-manifest.json"

signs:
  - artifacts: checksum
    args: ["--detach-sign"]

release:
  github:
    owner: fortinet
    name: terraform-provider-fortiappseccloud
    draft: false

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
